### ISSUE TITLE
Updated source code

### ISSUE THREAD

**Issue by Christian-Roggia** [micrictor/stuxnet#1]
Hi micrictor,
since github has disabled the private messages between users and you do not provide any public email and/or contact I'm obligated to use this not-very-elegant way to contact you. This is the first time I've seen someone working on my sources and yeah, it is a little messed up. I've updated that sources, removed useless comments (as you did) and added a short description to (almost) every function. I haven't updated the public sources since I have a few more things I would've done, but I've got no time in the past months for that and to be honest I've lost my interest after acknowledging that the project wasn't followed by researchers (I'm aware that the code is hard to understand and that it misses of proper comments and descriptions).

If you are interested please contact me at the address christian.roggia@gmail.com (provided on google code as well), I would be more than happy to share the updates with you and have you working on my side.

(P.s. for shamoon/disttrack is the same as stuxnet)

Best regards,
Christian Roggia.

**Comment by micrictor** [comment]
Duly noted - I've edited my readme to link to your github repo instead of google code as well - but I'll continue working on my slightly outdated copy as an intellectual exercise.

**Comment by micrictor** [comment]
I don't know if you'll ever get this, as I don't know if you've remained active in github, but I've decided to( manually ) merge in your changes, and will be doing so in the next couple days. If you have any objection to me doing so, please e-mail me at mic.ric.tor@gmail.com, or drop a message here.

Thanks!
